config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :weekbgs

  resources :userreqs
    get 'school_classes/groups/:id/:id1/:group', to: 'school_classes#groups', as: 'school_classgroup'
  get 'users/timetable', to: 'users#timetable', as: 'user_timetable'
  get 'users/requisition', to: 'users#requisition', as: 'user_requisition'
    get 'users/newreq', to: 'users#newreq', as: 'user_newreq'
	get 'timetables/timetable', to: 'timetables#timetable', as: 'timetables_timetable'
	get 'users/techview', to: 'users#techview', as: 'user_techview'
  match 'timetables/all' => 'timetables#update_all', :as => :update_all, :via => :put
  resources :schoolclasses
  resources :rooms
  resources :contents
  resources :timetables
  resources :schools    
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :content, :day, :period, :room_id, :user_id, :week, :weekbg_id, :schoolclass_id, :pupilnumber
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new
	@weekbg= Weekbg.find(params[:weekbg_id])
	@week = params[:week]
	@day = params[:day]
	@period = params[:period]
	@room = params[:room_id]
	@schoolclass =params[:schoolclass]
	@thisclass = Schoolclass.find(params[:schoolclass])
	@pupilnumber = params[:pupilnumber]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
  
    @content = Content.new(params[:content])
	@content.user_id = current_user.id
    respond_to do |format|
      if @content.save
        format.html { redirect_to user_requisition_path(:id=>@content.weekbg_id,:week=>@content.week), notice: 'Content was successfully created.' }
        format.json { render json: user_requisition_path(:id=>@content.weekbg_id, :week=>@content.week), status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: user_requisition_path(:id=>@content.weekbg_id, :week=>@content.week).errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to user_requisition_path(:id=>@content.weekbg_id,:week=>@content.week), notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: user_requisition_path(:id=>@content.weekbg_id,:week=>@content.week).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%=f.hidden_field :weekbg_id, :value=>@weekbg.id%>
<%=f.hidden_field :day, :value=>@day%>
<%=f.hidden_field :period, :value=>@period%>
<%=f.hidden_field :week, :value=>@week%>
<%=f.hidden_field :schoolclass_id, :value=>@schoolclass%>
<%=f.hidden_field :pupilnumber, :value=>@pupilnumber%>
 <div>
 <%=@weekbg.date%>
 </div>
 
 <div>
 Week <%=@week%> | 
<%if @day=='1'%>
 Monday 
 <% end%>
 <%if @day=='2'%>
 Tuesday
 <% end%>
 <%if @day=='3'%>
 Wednesday
 <% end%>
 <%if @day=='4'%>
 Thursday
 <% end%>
 <%if @day=='5'%>
 Friday
 <% end%>
  | 
 Period <%=@period%>
 |
 <%=@thisclass.classname%>
 </div>
  <br />
 <div class="field">
<%= f.label :room_id%><br />
    <%= f.collection_select(:room_id, Room.all,:id ,:roomname, {:selected =>@room}, {:class=>"input-small"}) %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/_formedit.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_id %><br />
    <%= f.collection_select(:room_id, Room.all,:id ,:roomname , {},{:class=>"input-small"}) %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'formedit' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <tr>
    <th>User</th>
    <th>Weekbg</th>
    <th>Week</th>
    <th>Day</th>
    <th>Period</th>
    <th>Room</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contents.each do |content| %>
  <tr>
    <td><%= content.user_id %></td>
    <td><%= content.weekbg %></td>
    <td><%= content.week %></td>
    <td><%= content.day %></td>
    <td><%= content.period %></td>
    <td><%= content.room_id %></td>
    <td><%= content.content %></td>
    <td><%= link_to 'Show', content %></td>
    <td><%= link_to 'Edit', edit_content_path(content) %></td>
    <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>Enter your Requisition Details</h1>

<%= render 'form' %>

<%= link_to('Back', user_requisition_path(:id=>@weekbg.id, :week=>@week)) %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @content.user_id %>
</p>

<p>
  <b>Weekbg:</b>
  <%= @content.weekbg %>
</p>

<p>
  <b>Week:</b>
  <%= @content.week %>
</p>

<p>
  <b>Day:</b>
  <%= @content.day %>
</p>

<p>
  <b>Period:</b>
  <%= @content.period %>
</p>

<p>
  <b>Room:</b>
  <%= @content.room_id %>
</p>

<p>
  <b>Content:</b>
  <%= @content.content %>
</p>


<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>