config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :weekbgs

  resources :userreqs
    get 'school_classes/groups/:id/:id1/:group', to: 'school_classes#groups', as: 'school_classgroup'
  get 'users/timetable', to: 'users#timetable', as: 'user_timetable'
  get 'users/requisition', to: 'users#requisition', as: 'user_requisition'
    get 'users/newreq', to: 'users#newreq', as: 'user_newreq'
	get 'timetables/timetable', to: 'timetables#timetable', as: 'timetables_timetable'
	get 'users/techview', to: 'users#techview', as: 'user_techview'
  match 'timetables/all' => 'timetables#update_all', :as => :update_all, :via => :put
  resources :schoolclasses
  resources :rooms
  resources :contents
  resources :timetables
  resources :schools    
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  # GET /timetables
  # GET /timetables.json
  def index
    @timetables = Timetable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timetables }
    end
	end

	def update_all
	params['timetable'].keys.each do |id|
    @timetable = Timetable.find(id.to_i)
	@timetable.update_attributes(params['timetable'][id])
  end
  session[:return_to] ||= request.referer
redirect_to user_timetable_path(:week=>@timetable.week)
	end
	
	def timetable
		@user = User.where("id = ?", current_user.id).first
		@periods = School.where("id = ?", @user.school_id).first
		
	end
	
	
  # GET /timetables/1
  # GET /timetables/1.json
  def show
    @timetable = Timetable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timetable }
    end
  end

  
  # GET /timetables/new
  # GET /timetables/new.json
  def new
	
	@timetable = Timetable.new
	

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timetable }
    end
  end

  # GET /timetables/1/edit
  def edit
    @timetable = Timetable.find(params[:id])
  end

  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = Timetable.new(params[:timetable])

    respond_to do |format|
      if @timetable.save
        format.html { redirect_to @timetable, notice: 'Timetable was successfully created.' }
        format.json { render json: @timetable, status: :created, location: @timetable }
      else
        format.html { render action: "new" }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timetables/1
  # PUT /timetables/1.json
  def update
    @timetable = Timetable.find(params[:id])

    respond_to do |format|
      if @timetable.update_attributes(params[:timetable])
        format.html { redirect_to @timetable, notice: 'Timetable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable = Timetable.find(params[:id])
    @timetable.destroy

    respond_to do |format|
      format.html { redirect_to timetables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/timetables/_form.html.erb
<%= form_for(@timetable) do |f| %>
  <% if @timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% @timetable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :week %><br />
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%= f.number_field :period %>
  </div>
  <div class="field">
    <%= f.label :room_id %><br />
    <%= f.number_field :room_id %>
  </div>
  <div class="field">
    <%= f.label :class_id %><br />
    <%= f.number_field :class_id %>
  </div>
  <div class="field">
    <%= f.label :pupilnumber %><br />
    <%= f.number_field :pupilnumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1>Editing timetable</h1>

<%= render 'form' %>

<%= link_to 'Show', @timetable %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/index.html.erb
<h1>Listing timetables</h1>

<table>
  <tr>
     <th>Week</th>
    <th>Day</th>
    <th>Period</th>
    <th>Room</th>
    <th>Class</th>
    <th>Pupilnumber</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @timetables.each do |timetable| %>
  <tr>
    <td><%= timetable.week %></td>
    <td><%= timetable.day %></td>
    <td><%= timetable.period %></td>
    <td><%= timetable.room_id %></td>
    <td><%= timetable.schoolclass_id %></td>
    <td><%= timetable.pupilnumber %></td>
    <td><%= link_to 'Show', timetable %></td>
    <td><%= link_to 'Edit', edit_timetable_path(timetable) %></td>
    <td><%= link_to 'Destroy', timetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Timetable', new_timetable_path %>

app/views/timetables/new.html.erb
<h1>New timetable</h1>

<%= render 'form' %>
<%= @periods %>
<table>



</table>


<%= link_to 'Back', timetables_path %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @timetable.user_id %>
</p>

<p>
  <b>Week:</b>
  <%= @timetable.week %>
</p>

<p>
  <b>Day:</b>
  <%= @timetable.day %>
</p>

<p>
  <b>Period:</b>
  <%= @timetable.period %>
</p>

<p>
  <b>Room:</b>
  <%= @timetable.room_id %>
</p>

<p>
  <b>Class:</b>
  <%= @timetable.class_id %>
</p>

<p>
  <b>Pupilnumber:</b>
  <%= @timetable.pupilnumber %>
</p>


<%= link_to 'Edit', edit_timetable_path(@timetable) %> |
<%= link_to 'Back', timetables_path %>

app/views/timetables/timetable.html.erb
<h1>Timetable</h1>

<%= form_for :timetables, :url => update_all_path, :html => { :method => :put } do %>
<%y=5%>
<%x=@periods.periods%>
<%j=@periods.weeks %>
<table>
<% (1..j).each do |j| %>
<tr>
<td>
<h2>Week <%=j%></h2>
<table >
<% (1..x).each do |i| %>
<tr>
<% (1..y).each do |y| %>
<td style="border: 2px solid #000000">

<table>
<tr>

<td>
<%= fields_for "timetable[]", y do |f| %>
    <%= f.hidden_field :user_id, :value=>current_user.id %>
    <%= f.hidden_field :week, :value=>j %>
    <%= f.hidden_field :day, :value=>y %>
    <% f.hidden_field :period, :value=>i %>
    <%= f.label :room_id %>
	</td>
	<td>
    <%= f.collection_select(:room_id, Room.all,:id, :roomname) %>
	</td>
</tr>
<tr>
<td>
<%= f.label :schoolclass_id %>
</td>
<td> 
<%= f.collection_select(:schoolclass_id, @schoolclasses, :id, :classname) %>
</td></tr>
<tr><td>
  <%= f.label 'Pupils' %>
</td>
<td>
<%= f.select(:pupilnumber, 1..35, {:prompt => "N/A"})	 %>
</td>
</tr>
</table>
 </td>
  <% end %>
</tr>

<% end %>
</table>
<td>
<tr>
<% end %>
<% end %>
</table>
      <%= f.submit "Save Timetable", class: "btn btn-large btn-primary" %>
<% end %>