config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :weekbgs

  resources :userreqs
    get 'school_classes/groups/:id/:id1/:group', to: 'school_classes#groups', as: 'school_classgroup'
  get 'users/timetable', to: 'users#timetable', as: 'user_timetable'
  get 'users/requisition', to: 'users#requisition', as: 'user_requisition'
    get 'users/newreq', to: 'users#newreq', as: 'user_newreq'
	get 'timetables/timetable', to: 'timetables#timetable', as: 'timetables_timetable'
	get 'users/techview', to: 'users#techview', as: 'user_techview'
  match 'timetables/all' => 'timetables#update_all', :as => :update_all, :via => :put
  resources :schoolclasses
  resources :rooms
  resources :contents
  resources :timetables
  resources :schools    
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/schoolclasses_controller.rb
class SchoolclassesController < ApplicationController
  # GET /schoolclasses
  # GET /schoolclasses.json
  def index
    @schoolclasses = Schoolclass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schoolclasses }
    end
  end

  # GET /schoolclasses/1
  # GET /schoolclasses/1.json
  def show
    @schoolclass = Schoolclass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schoolclass }
    end
  end

  # GET /schoolclasses/new
  # GET /schoolclasses/new.json
  def new
    @schoolclass = Schoolclass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schoolclass }
    end
  end

  # GET /schoolclasses/1/edit
  def edit
    @schoolclass = Schoolclass.find(params[:id])
  end

  # POST /schoolclasses
  # POST /schoolclasses.json
  def create
    @schoolclass = Schoolclass.new(params[:schoolclass])

    respond_to do |format|
      if @schoolclass.save
        format.html { redirect_to @schoolclass, notice: 'Schoolclass was successfully created.' }
        format.json { render json: @schoolclass, status: :created, location: @schoolclass }
      else
        format.html { render action: "new" }
        format.json { render json: @schoolclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schoolclasses/1
  # PUT /schoolclasses/1.json
  def update
    @schoolclass = Schoolclass.find(params[:id])

    respond_to do |format|
      if @schoolclass.update_attributes(params[:schoolclass])
        format.html { redirect_to @schoolclass, notice: 'Schoolclass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schoolclass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schoolclasses/1
  # DELETE /schoolclasses/1.json
  def destroy
    @schoolclass = Schoolclass.find(params[:id])
    @schoolclass.destroy

    respond_to do |format|
      format.html { redirect_to schoolclasses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schoolclasses_helper.rb
module SchoolclassesHelper
end

app/views/schoolclasses/_form.html.erb
<%= form_for(@schoolclass) do |f| %>
  <% if @schoolclass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schoolclass.errors.count, "error") %> prohibited this schoolclass from being saved:</h2>

      <ul>
      <% @schoolclass.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :classname %><br />
    <%= f.text_field :classname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schoolclasses/edit.html.erb
<h1>Editing schoolclass</h1>

<%= render 'form' %>

<%= link_to 'Show', @schoolclass %> |
<%= link_to 'Back', schoolclasses_path %>

app/views/schoolclasses/index.html.erb
<h1>Listing schoolclasses</h1>

<table>
  <tr>
    <th>Classname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schoolclasses.each do |schoolclass| %>
  <tr>
    <td><%= schoolclass.classname %></td>
    <td><%= link_to 'Show', schoolclass %></td>
    <td><%= link_to 'Edit', edit_schoolclass_path(schoolclass) %></td>
    <td><%= link_to 'Destroy', schoolclass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schoolclass', new_schoolclass_path %>

app/views/schoolclasses/new.html.erb
<h1>New schoolclass</h1>

<%= render 'form' %>

<%= link_to 'Back', schoolclasses_path %>

app/views/schoolclasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Classname:</b>
  <%= @schoolclass.classname %>
</p>


<%= link_to 'Edit', edit_schoolclass_path(@schoolclass) %> |
<%= link_to 'Back', schoolclasses_path %>